services:
  reverse-proxy:
    container_name: reverse-proxy
    image: traefik:latest

    ports:
      #Allowing external request
      - "80:80"
      - "443:443"
      - "3000:3000"
      - "8080:8080"
    networks:
      - network0
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - ./traefik/config.yml:/etc/traefik/config.yml
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - network0
    ports:
      - "8081:80" #Bypass

  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    networks:
      - network0
    ports:
      - "3001:3000" #Bypass
    
networks:
  network0:
    driver: bridge