services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - network0
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    networks:
      - network0

networks:
  network0:
    driver: bridge